defaults:
  - base_env

_target_: scalebridge.env.motion_tracking.MotionTrackingEnv
_recursive_: False
config:
  motion_path: scalebridge/data/motion/g1_29dof/squat.npz
  future_idx: [0,1,2,3,4,5]
  reference_forcing: True
